fix can handle for catch all activator
just-ai/jaicf-kotlin pull request #109
Opened 2020-11-06 11:09 UTC by Denire

2020-11-06 11:11 UTC, nikvoloshin approved these changes

2020-11-06 14:19 UTC, morfeusys approved these changes

2020-11-10 08:10 UTC, nikvoloshin requested changes
@Denire sorry, I missed this during the review, fix documentation please, for now it states that `this activator handles everything except events`

2020-11-10 11:39 UTC, morfeusys approved these changes

2020-11-20 09:16 UTC, nikvoloshin approved these changes

2020-11-20 09:59 UTC, merged