Add ActivatorContext predicates to intent and event ActivationRules
just-ai/jaicf-kotlin pull request #145
Opened 2021-03-02 10:41 UTC by nikvoloshin

2021-03-02 13:15 UTC, Denire requested changes

2021-03-02 13:15 UTC, Denire commented on core/src/main/kotlin/com/justai/jaicf/activator/event/EventActivationRule.kt
> +abstract class EventActivationRule(val matches: (EventActivatorContext) -> Boolean): ActivationRule
I think EventActivatorContext must become an open class.

2021-03-05 15:58 UTC, Denire approved these changes

2021-03-09 12:46 UTC, morfeusys approved these changes

2021-03-09 12:47 UTC, merged