Add properties to TelephonyBotRequest
just-ai/jaicf-kotlin pull request #187
Opened 2021-07-23 09:58 UTC by veptechno

Add missing properties to TelephonyBotRequest

2021-07-23 10:18 UTC, nikvoloshin requested changes

2021-07-23 10:18 UTC, nikvoloshin commented on channels/jaicp/src/main/kotlin/com/justai/jaicf/channel/jaicp/dto/JaicpNativeBotRequest.kt
> +    fun getCallRecordingFullUrl(context: ActionContext<*, *, *>): String? =
Why not
`val DefaultActionContext.callRecordingFullUrl: String?`

or even
`val ActionContext<out ActivatorContext, TelephonyBotRequest, TelephonyReactions, *>.callRecordingFullUrl: String?`

2021-07-23 10:18 UTC, nikvoloshin commented on channels/jaicp/src/main/kotlin/com/justai/jaicf/channel/jaicp/dto/JaicpNativeBotRequest.kt
> +        get() = jaicp.rawRequest.jsonObject["originateData"]?.jsonObject?.get("callScenarioData")
Please, consider moving common code to a separate function

2021-07-23 10:18 UTC, nikvoloshin commented on channels/jaicp/src/main/kotlin/com/justai/jaicf/channel/jaicp/dto/JaicpNativeBotRequest.kt
> +        jaicp.data?.jsonObject?.get("resterisk")?.jsonObject?.get("callRecordsDownloadData")
Please, consider moving common code to a function

2021-07-23 12:46 UTC, nikvoloshin approved these changes

2021-07-26 12:28 UTC, Denire approved these changes

2021-07-27 10:17 UTC, merged