Add a new telephony event and implement the mute function
just-ai/jaicf-kotlin pull request #188
Opened 2021-07-23 10:01 UTC by veptechno

Add a new telephony event and implement the mute function

2021-07-23 10:56 UTC, nikvoloshin requested changes

2021-07-23 10:56 UTC, nikvoloshin commented on channels/jaicp/src/main/kotlin/com/justai/jaicf/channel/jaicp/channels/ChatApiChannel.kt
> +            ChatWidgetChannel(botApi, liveChatProvider, mutedEvents)
ChatApiChannel, I guess

2021-07-23 10:56 UTC, nikvoloshin commented on channels/jaicp/src/main/kotlin/com/justai/jaicf/channel/jaicp/channels/JaicpNativeChannel.kt
> +    private val mutedEvents: List<String> = emptyList()
Don't we want to propagate this feature to all channels, not only jaicp ones?

2021-07-23 19:21 UTC, nikvoloshin approved these changes

2021-07-26 12:31 UTC, Denire approved these changes

2021-07-27 10:24 UTC, merged