Use GitHub actions for CI
just-ai/jaicf-kotlin pull request #200
Opened 2021-08-11 11:15 UTC by veptechno

Travis CI no longer works in this repository. 
This PR adds support for github actions and minor refactoring of MongoBotContextManagerTest to support an external database.

2021-08-11 12:02 UTC, morfeusys approved these changes

2021-08-11 16:19 UTC, Denire approved these changes

2021-08-13 08:44 UTC, nikvoloshin requested changes

2021-08-13 08:44 UTC, nikvoloshin commented on managers/mongo/src/test/kotlin/com/justai/jaicf/context/manager/test/MongoBotContextManagerTest.kt
> +@EnabledIfEnvironmentVariable(named = "mongo", matches = "external")
I'd suggest use CI-related env variables. Usually `CI: true` env var is used.
And it'd better make `port` env var to, so we'll be able to change CI configuration without changing the code.

So, I'd suggest change this to:
`@EnabledIfEnvironmentVariable("CI", "true")`
`val port = System.getenv("PORT")`

2021-08-13 13:41 UTC, nikvoloshin approved these changes

2021-08-13 14:02 UTC, merged