Implement mapdb context manager using Jackson for serialization
just-ai/jaicf-kotlin pull request #204
Opened 2021-08-17 15:35 UTC by veptechno

Now MapDbBotContextManager uses the serialization mechanism provided by java.io. This is inconvenient to use because it forces you to implement the Serializable interface for all classes that are stored in BotContext.

This PR adds a BotContextManager that uses MapDb and Jackson for serialization. 
**What's done**: created JacksonMapDbBotContextManager class, deprecated MapDbBotContextManager class, added tests for JacksonMapDbBotContextManager.

2021-08-17 20:29 UTC, Denire approved these changes

2021-08-18 13:38 UTC, nikvoloshin requested changes

2021-08-18 13:38 UTC, nikvoloshin commented on managers/mapdb/src/main/kotlin/com/justai/jaicf/context/manager/mapdb/BotContextModel.kt
> +internal class BotContextModel private constructor(): Serializable {
Did you check this change with the old MapDB manager? As far as old MapDB works with java.io.Serializable we should double-check all changes in serializable classes

2021-08-18 13:38 UTC, nikvoloshin commented on managers/mapdb/src/main/kotlin/com/justai/jaicf/context/manager/mapdb/BotContextModel.kt
> +internal class BotContextModel private constructor(): Serializable {
Also, we shouldn't change the visibility of public classes.
And anyway, I'd suggest remaining all old code unchanged and mark it deprecated.
And implement jackson-mapdb as completely new manager

2021-08-18 13:38 UTC, nikvoloshin commented on managers/mapdb/src/main/kotlin/com/justai/jaicf/context/manager/mapdb/MapDbBotContextManager.kt
> +    ReplaceWith(
Let's not add replace with here. If a user will decide to use this quick fix, he will break his db-file

2021-08-18 13:38 UTC, nikvoloshin commented on managers/mapdb/src/main/kotlin/com/justai/jaicf/context/manager/mapdb/MapDbBotContextManager.kt
> +    ReplaceWith(
Also, let's add incompatibility notice in deprecation message

2021-08-25 08:01 UTC, nikvoloshin approved these changes

2021-09-13 10:28 UTC, merged