Add ChannelFactory companion object to all channels
just-ai/jaicf-kotlin pull request #205
Opened 2021-08-17 18:26 UTC by veptechno

Now when passing in BotEngine some channels (Alice, Viber, Google) need to specify .Factory(), which is different from other channels and causes confusion.
This PR adds companion objects implemented by JaicpChannelFactory to these channels and allows you to pass channels like other

2021-08-18 21:08 UTC, Denire approved these changes

2021-08-25 08:22 UTC, nikvoloshin requested changes

2021-08-25 08:22 UTC, nikvoloshin commented on channels/google-actions/src/main/kotlin/com/justai/jaicf/channel/googleactions/jaicp/ActionsFulfillmentDialogflow.kt
> +    companion object : JaicpCompatibleChannelFactory {
Let's use [delegation](https://kotlinlang.org/docs/delegation.html) for easier inheritance
```suggestion
    companion object : JaicpCompatibleChannelFactory by ActionsFulfillmentDialogflow()
```

2021-08-25 08:22 UTC, nikvoloshin commented on channels/google-actions/src/main/kotlin/com/justai/jaicf/channel/googleactions/jaicp/ActionsFulfillmentSDK.kt
> +    companion object : JaicpCompatibleChannelFactory {
The same about delegation

2021-08-25 08:22 UTC, nikvoloshin commented on channels/viber/src/main/kotlin/com/justai/jaicf/channel/viber/ViberChannel.kt
> +    companion object : JaicpCompatibleAsyncChannelFactory {
The same about delegation

2021-08-25 08:22 UTC, nikvoloshin commented on channels/yandex-alice/src/main/kotlin/com/justai/jaicf/channel/yandexalice/AliceChannel.kt
> +    companion object : JaicpCompatibleChannelFactory {
The same about delegation

2021-08-25 08:43 UTC, nikvoloshin approved these changes

2021-08-25 08:46 UTC, merged