Fix/add ssml support
just-ai/jaicf-kotlin pull request #258
Opened 2024-01-23 09:57 UTC by Yamakuprina

2024-01-23 10:50 UTC, CptBronzebeard requested changes

2024-01-23 10:50 UTC, CptBronzebeard commented on channels/jaicp/src/main/kotlin/com/justai/jaicf/channel/jaicp/reactions/TelephonyReactions.kt
> +            replies.add(TextReply(text, state = currentState, tts = tts))
Выглядит как дублирование логики + перемешение уровней абстракции
Хотелось бы, чтобы вся логика была вынесена в say(text), тем более в случае bargeIn'а она уже там

2024-01-24 08:46 UTC, Yamakuprina commented on channels/jaicp/src/main/kotlin/com/justai/jaicf/channel/jaicp/reactions/TelephonyReactions.kt
> +            replies.add(TextReply(text, state = currentState, tts = tts))
Не уверен, что корректно тебя понял. Нести изменения в метод JaicpReactions.say нет нужды и желания, поскольку функционал касается исключительно телефонии. Есть возможность перенести этот кусок кода в метод https://github.com/just-ai/jaicf-kotlin/blob/1f7109b924446128aaa4b4293fa882ef92556690/channels/jaicp/src/main/kotlin/com/justai/jaicf/channel/jaicp/reactions/TelephonyReactions.kt#L54

2024-01-24 10:26 UTC, Yamakuprina commented on channels/jaicp/src/main/kotlin/com/justai/jaicf/channel/jaicp/reactions/TelephonyReactions.kt
> +            replies.add(TextReply(text, state = currentState, tts = tts))
Вынес в отдельный метод

2024-01-25 12:05 UTC, CptBronzebeard approved these changes

2024-01-25 12:06 UTC, merged