Slotfilling interfaces, slotfilling implementation for Caila and CailaIntentActivator improvements
just-ai/jaicf-kotlin pull request #27
Opened 2020-07-25 22:04 UTC by Denire

This pull request will add slotfilling feature to JAICF. It also will create first slotfilling implementation for Caila NLU provider along will minor improvements in Caila NLU features.

A bit about improvements in Caila NLU:
1. Caila will now return a list of possible intents
2. Caila will now return more detailed NLU data - phrase markup and all the entities in phrase.

2020-07-27 08:02 UTC, morfeusys commented on core/src/main/kotlin/com/justai/jaicf/slotfilling/SlotFiller.kt
> + * It can be useful, for example, if you want to create channel-specific slot filling,
to create channel-specific slot filling **reactions**

2020-07-27 08:02 UTC, morfeusys commented on core/src/main/kotlin/com/justai/jaicf/slotfilling/SlotFiller.kt
> +     * Tells if it's possible to fill custom this slot with your own code.
Please review this comment

2020-07-27 08:03 UTC, morfeusys commented on core/src/main/kotlin/com/justai/jaicf/slotfilling/SlotFiller.kt
> +     * @return true if can handle, no if can not
Please review this comment

2020-07-27 08:03 UTC, morfeusys commented on core/src/main/kotlin/com/justai/jaicf/slotfilling/SlotFiller.kt
> +     * @param name - name of slot to handle
name of slot to be handled

2020-07-27 08:04 UTC, morfeusys commented on core/src/main/kotlin/com/justai/jaicf/slotfilling/SlotFillingResult.kt
> +    val activatorContext: ActivatorContext
Please describe this parameter

2020-08-13 14:03 UTC, morfeusys commented on activators/caila/src/main/kotlin/com/justai/jaicf/activator/caila/slotfilling/CailaSlotfillingHelper.kt
> +internal class CailaSlotfillingHelper(
Camel-case here please

2020-08-13 14:05 UTC, morfeusys commented on activators/caila/src/main/kotlin/com/justai/jaicf/activator/caila/CailaIntentActivator.kt
> +    private val slotFillingHelper = CailaSlotfillingHelper(client)
How can I override a default slot filling settings?

2020-08-13 14:08 UTC, morfeusys commented on activators/caila/src/main/kotlin/com/justai/jaicf/activator/caila/slotfilling/CailaSlotfillingHelper.kt
> +    private fun getSlotfillingContext(botContext: BotContext): CailaSlotFillingContext? {
Why do you need a client ID again?

2020-08-13 14:12 UTC, morfeusys commented on activators/caila/src/main/kotlin/com/justai/jaicf/activator/caila/slotfilling/CailaSlotfillingHelper.kt
> +                    saveSlotFillingContext(botContext, ctx)
Did you ever test this persistence with some context managers like mongo or mapdb?

2020-08-13 14:13 UTC, morfeusys commented on activators/caila/src/main/kotlin/com/justai/jaicf/activator/caila/slotfilling/CailaSlotfillingHelper.kt
> +        private fun getSlotfillingKey(clientId: String) = "$clientId-slotfilling-context"
Fix naming please

2020-08-13 14:13 UTC, morfeusys commented on activators/caila/src/main/kotlin/com/justai/jaicf/activator/caila/slotfilling/CailaSlotfillingHelper.kt
> +    private fun getSlotfillingContext(botContext: BotContext): CailaSlotFillingContext? {
Fix naming please

2020-08-13 14:14 UTC, morfeusys commented on core/src/main/kotlin/com/justai/jaicf/slotfilling/SlotFillingResult.kt
> + * @param activatorContext initially stored activator context. New slots can be added to this context to be available in scenario.
"New slots SHOULD be added"

2020-08-18 10:58 UTC, Denire commented
@morfeusys Thank you for such useful comments!

After your last review I've changed or fixed:
1. Persistence with mapdb / mongo
2. Naming - use camelcase (SlotFilling instead of Slotfilling)
3. Added missing javadocs, or fixed bad javadocs
4. CailaIntentActivator intent selection logic (now by context + confidence)
5. Interface naming (SlotFiller -> SlotFillingReactionsProcessor), which now has methods canProcess and process

2020-08-20 07:16 UTC, morfeusys requested changes

2020-08-20 07:16 UTC, morfeusys commented on core/src/main/kotlin/com/justai/jaicf/slotfilling/SlotFillingBotContextExt.kt
> +internal fun BotContext.setSlotFillingIsFinished() = session.remove(SLOTFILLING_ACTIVATOR_KEY)
By fact, this function doesn't set anything. I'd rename it to `finishSlotFilling`

2020-08-20 07:16 UTC, morfeusys commented on activators/caila/src/main/kotlin/com/justai/jaicf/activator/caila/slotfilling/CailaSlotFillingHelper.kt
> +                    if (slotFillingReactionsProcessor != null && slotFillingReactionsProcessor.canProcess(slot.name)) {
`slotFillingReactionsProcessor?.canProcess(slot.name) == true`?

2020-08-20 07:16 UTC, morfeusys commented on activators/caila/src/main/kotlin/com/justai/jaicf/activator/caila/slotfilling/CailaSlotFillingHelper.kt
> +        private const val SLOTFILLING_CONTEXT_KEY = "com/justai/jaicf/activator/caila/slotfilling/context"
Why not to use dots instead of slashes?

2020-08-20 07:16 UTC, morfeusys commented on activators/caila/src/main/kotlin/com/justai/jaicf/activator/caila/slotfilling/CailaSlotFillingContext.kt
> +@Serializable
Are you sure we need kotlinx serializable here?

2020-08-20 16:10 UTC, Denire commented
@morfeusys Thank you again, i'll sum up here:
1. Dots can be used in mongodb key only since 3.6, therefore I decided to use slashes to permit clients using mongo <3.6
2. SlotFillingReactionsProcessor was renamed to SlotReactor with methods canReact(...) and react(...), with improved javadocs.
3. Other points from your comments were fixed.

2020-08-20 17:03 UTC, morfeusys approved these changes
Good job @Denire !

2020-08-20 17:26 UTC, merged