[#55] MDCContext and gelf-appender for graylog
just-ai/jaicf-kotlin pull request #77
Opened 2020-10-06 23:27 UTC by Denire

This PR adds transitive dependencies for gelf appenders for graylog and ensures fields for JAICP logging, such as accountId, channelId and requestId.

2020-10-07 08:02 UTC, morfeusys requested changes

2020-10-07 08:02 UTC, morfeusys commented on channels/jaicp/src/main/kotlin/com/justai/jaicf/channel/jaicp/dto/JaicpBotRequest.kt
> +    init {
Are you sure MDC propagation should be placed to the constructor of the data class?

2020-10-07 11:07 UTC, Denire commented on channels/jaicp/src/main/kotlin/com/justai/jaicf/channel/jaicp/JaicpConnector.kt
> +        MDC.put("accountId", it.first().second.accountId)
In case channels are empty CA returns 404 now, therefore channels should have first.

2020-10-08 08:54 UTC, morfeusys approved these changes

2020-10-08 08:58 UTC, merged